# Generated by Django 6.1 on 2026-09-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_product_author_alter_product_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
