# Generated by Django 6.1 on 2026-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('draft', 'Черновик')], default='draft', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eshop_images/'),
        ),
    ]
